platform :ios ,'8.0'
use_frameworks!

target 'MBWB' do 

pod 'MJExtension'

pod 'SDWebImage', '~>3.7'

pod 'AFNetworking', '~> 3.0'

pod 'MBProgressHUD', '~> 0.9.2'

pod 'MJRefresh'

pod 'FDFullscreenPopGesture', '1.1'

project 'MBWB.project'

end 

